# This is an example .goreleaser.yml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    - go generate ./pkg/version
builds:
  - id: default
    env:
      - CGO_ENABLED=0
    goos:
#      - linux
#      - windows
      - darwin
    goarch:
      - amd64
#      - arm64
    # 使用 ldflags="-s -w" 去掉符号表和调试信息，以减少发布包的大小
    ldflags:
      - -s
      - -w
    ignore:
      - goos: linux
        goarch: arm64
      - goos: windows
        goarch: arm64
    main: .
archives:
  - id: default
    builds:
      - default
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip
checksum:
  name_template: 'checksums.txt'
changelog:
  use: github
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

release:
  github:
    owner: howieyuen
    name: kusion
  draft: false
  footer: |
    ## Docker Images
    * `howieyuen/kusion:{{ .Env.KUSION_VERSION }}`
    
    ## Dependent version
    * [kclvm-go](https://github.com/howieyuen/kclvm-go): `{{ .Env.KCLVM_GO_VERSION }}`
    * [kcl-plugin](https://github.com/howieyuen/kcl-plugin): `{{ .Env.KCL_PLUGIN_VERSION }}`

brews:
  - tap:
      owner: howieyuen
      name: homebrew-tap
      token: "{{ .Env.TAP_GITHUB_TOKEN }}"
    url_template: "https://github.com/howieyuen/kusion/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    download_strategy: CurlDownloadStrategy
    # Git author used to commit to the repository.
    # Defaults are shown.
    commit_author:
      name: GoReleaser Bot
      email: goreleaser@carlosbecker.com
    folder: HomebrewFormula
    homepage: "https://github.com/howieyuen/kusion"
    description: "Codify and deliver intentions to Kubernetes and Clouds"
    license: "Apache License"
    skip_upload: false
    dependencies:
      - name: kcl-lang/tap/kclvm
    test: |
      system "#{bin}/kusion version"
